######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 12 12:45:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BallDialog.h
SOURCES += BallDialog.cpp main.cpp
