######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 10 12:50:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.h
SOURCES += ball.cpp main.cpp
