######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 4 16:03:56 2010
######################################################################

TEMPLATE = app
TARGET = ../task7
DEPENDPATH += .
INCLUDEPATH += .
QT          += testlib

# Input
HEADERS += Test.h ../src/TimeDialog.h
SOURCES += main.cpp Test.cpp ../src/TimeDialog.cpp
