# #####################################################################
# Automatically generated by qmake (2.01a) ?? ???. 3 15:50:24 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += src.h
SOURCES += src.cpp \
    main.cpp
