######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 10 16:40:57 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BouncedBall.h
SOURCES += BouncedBall.cpp main.cpp
