######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 29 03:21:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BouncedBall.h
SOURCES += BouncedBall.cpp main.cpp
