######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 27 12:21:49 2010
######################################################################

TEMPLATE = subdirs
TARGET = 
DEPENDPATH += . Table Pult
#INCLUDEPATH += . Pult Table

# Input
#HEADERS += Pult/Pult.h Table/Table.h
#SOURCES += Pult/main.cpp Pult/Pult.cpp Table/main.cpp Table/Table.cpp
SUBDIRS += Table Pult
