######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 21 21:32:13 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT           += network

# Input
HEADERS += Pult.h Table.h
SOURCES += main.cpp Pult.cpp Table.cpp
