######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 1 05:16:51 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network xml

# Input
HEADERS += RemoteController.h
SOURCES += main.cpp RemoteController.cpp
