######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 21:44:05 2010
######################################################################

TEMPLATE = app
TARGET = ../runTests 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TestTimers.h ../src/TimerDialog.h
SOURCES += main.cpp TestTimers.cpp ../src/TimerDialog.cpp

QT += testlib
