######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 30 00:07:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Counter.h
SOURCES += Counter.cpp main.cpp
