######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 27 15:10:44 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calculator.h
FORMS += Calculator.ui
SOURCES += Calculator.cpp main.cpp
