# #####################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 19:10:32 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calculator.h \
    Log.h
SOURCES += Calcuator.cpp \
    Log.cpp \
    main.cpp
FORMS += Log.ui
