######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 2 12:20:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Ball.h BallDialog.h Racket.h
SOURCES += Ball.cpp BallDialog.cpp main.cpp Racket.cpp

QT += network xml
