######################################################################
# Automatically generated by qmake (2.01a) ?? 10. ??? 22:56:33 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += circle.h
SOURCES += circle.cpp main.cpp
