######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 10 07:21:33 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LoggerWindow.h
SOURCES += LoggerWindow.cpp main.cpp
