######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 10:50:29 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += task2.h
SOURCES += main.cpp task2.cpp
