######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 1 16:17:04 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TimerDialog.h
SOURCES += main.cpp TimerDialog.cpp
