######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 14:54:33 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Dialog.h Timer.h
SOURCES += Dialog.cpp main.cpp Timer.cpp
