######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 23 19:51:19 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT           += network

# Input
HEADERS += Chat.h
SOURCES += Chat.cpp main.cpp
