######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 17 14:07:45 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyCalc.h myWindow.h
SOURCES += main.cpp MyCalc.cpp myWindow.cpp
