######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 17 23:32:05 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calcdockwgt.h calculator.h
SOURCES += calcdockwgt.cpp calculator.cpp main.cpp
