######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 10 22:06:30 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BouncingBall.h
SOURCES += BouncingBall.cpp main.cpp
