######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 14 14:29:51 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MagicBall.h
SOURCES += MagicBall.cpp main.cpp
