######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 21 00:35:29 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calcdockwgt.h calculator.h
SOURCES += calcdockwgt.cpp calculator.cpp main.cpp
