######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 26 23:22:15 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
