######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 3 21:24:20 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

HEADERS += MyDialog.h \
    timer.h
SOURCES += MyDialog.cpp \
    main.cpp \
    timer.cpp
