######################################################################
# Automatically generated by qmake (1.07a) Sun Sep 26 21:41:29 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
