# #####################################################################
# Automatically generated by qmake (2.01a) ?? ???. 2 05:41:15 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += gui core
# Input
HEADERS += TimerDialog.h
SOURCES += TimerDialog.cpp \
    main.cpp 
