######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 29 00:52:57 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += IntervalThread.h TimerDialog.h
SOURCES += IntervalThread.cpp main.cpp TimerDialog.cpp
