######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 3 22:30:26 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += 1.cpp
