######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 2 05:34:25 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += network xml
# Input
HEADERS += ArcanoidDialog.h BallAndRocket.h
SOURCES += AcranoidDialog.cpp BallAndRocket.cpp main.cpp
