######################################################################
# Automatically generated by qmake (1.07a) Sun Oct 3 13:32:09 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
