######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 14 14:43:30 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
