######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 10 22:05:23 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Dialog.h
SOURCES += Dialog.cpp main.cpp
