######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 30 22:15:36 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Dialog.h
SOURCES += Dialog.cpp main.cpp
