######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 5 14:56:06 2010
######################################################################

TEMPLATE = subdirs
TARGET = 
DEPENDPATH += . src tst
INCLUDEPATH += . src tst

# Input
HEADERS += src/TimeDialog.h tst/Test.h
SOURCES += src/main.cpp src/TimeDialog.cpp tst/main.cpp tst/Test.cpp
SUBDIRS += src tst
