######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 28 23:21:24 2010
######################################################################

TEMPLATE = app
TARGET = ../program
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += timersdialog.h
SOURCES += main.cpp timersdialog.cpp
