######################################################################
# Automatically generated by qmake (2.01a) ?? 24. ??? 20:25:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += udpchat.h
SOURCES += main.cpp udpchat.cpp
