######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 22 03:17:15 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
