######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 18 01:56:25 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calculator.h LogWindow.h
SOURCES += Calculator.cpp LogWindow.cpp main.cpp
