# #####################################################################
# Automatically generated by qmake (2.01a) Tue Sep 28 23:21:24 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += timersdialog.h \
    timerthread.h \
    myatomicint.h
SOURCES += main.cpp \
    timersdialog.cpp \
    timerthread.cpp \
    myatomicint.cpp
FORMS += timersdialog.ui
