######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 24 23:15:04 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myDialog.h
SOURCES += main.cpp myDialog.cpp
QT += network
