######################################################################
# Automatically generated by qmake (1.07a) Mon Nov 15 02:03:12 2010
######################################################################

TEMPLATE = app
TARGET = ../Game
QT += network xml
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Game.h
SOURCES += Game.cpp main.cpp
