######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 14 16:03:34 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib
# Input
HEADERS += test.h ../src/Dialog.h
SOURCES += main.cpp test.cpp ../src/Dialog.cpp
