######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 29 19:44:59 2010
######################################################################

TEMPLATE = app
TARGET = ../testCounter
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TestCounter.h ../src/Counter.h
SOURCES += main.cpp TestCounter.cpp ../src/Counter.cpp
QT += testlib
