# #####################################################################
# Automatically generated by qmake (2.01a) ?? ????. 26 13:46:19 2010
# #####################################################################
TEMPLATE = app
TARGET = Ballolo
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Ballolo.cpp \
    main.cpp
HEADERS = Ballolo.h
