######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 10 07:16:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BallWidget.h
SOURCES += BallWidget.cpp main.cpp
