######################################################################
# Automatically generated by qmake (1.07a) Sun Oct 24 11:12:29 2010
######################################################################

QT += network
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Chat.h
SOURCES += Chat.cpp main.cpp
