######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 26 14:36:59 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += QtApp.cpp
