######################################################################
# Automatically generated by qmake (2.01a) ?? 3. ??? 22:55:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += timerdialog.h
SOURCES += main.cpp timerdialog.cpp
