######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 10 20:22:32 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BallDialog.h
SOURCES += BallDialog.cpp main.cpp
