######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 21:04:41 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TimerDialog.h \
    threadtimer.h
SOURCES += main.cpp TimerDialog.cpp \
    threadtimer.cpp
