######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 1 03:30:24 2010
######################################################################

QT += network xml

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .


# Input
HEADERS += Arcanoid.h MyXMLHandler.h
SOURCES += Arcanoid.cpp MainArcanoid.cpp MyXmlHandler.cpp
