######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 18 04:00:32 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Calculator.h MainWindow.h
SOURCES += Calculator.cpp main.cpp MainWindow.cpp
