######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 23:10:49 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BallWidget.h
SOURCES += BallWidget.cpp main.cpp
