######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 2 16:21:21 2010
######################################################################

TEMPLATE = app
TARGET = ../timedialog
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TimeDialog.h
SOURCES += main.cpp TimeDialog.cpp
