######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 2 02:13:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Control.h SaxHandler.h
SOURCES += Control.cpp main.cpp SaxHandler.cpp
QT += xml
QT += network
