######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 29 01:03:50 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Timer.h TimerDialog.h
SOURCES += main.cpp Timer.cpp TimerDialog.cpp
