######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 31 23:51:31 2010
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyChat.h
SOURCES += main.cpp MyChat.cpp
