######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 25 02:35:41 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += MyChat.h
SOURCES += main.cpp MyChat.cpp
