######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 27 20:46:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
