######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 30 07:15:50 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h LogWindow.h
FORMS += LogWindow.ui
SOURCES += CalculatorDialog.cpp LogWindow.cpp main.cpp
