######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 9 22:40:37 2010
######################################################################

TEMPLATE = app
TARGET = ../mydialog
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyDialog.h
SOURCES += main.cpp MyDialog.cpp
