######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 9 22:41:02 2010
######################################################################

TEMPLATE = app
TARGET = ../runtests
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += Test1.h ../src/MyDialog.h
SOURCES += main.cpp Test1.cpp ../src/MyDialog.cpp
