######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 14 14:44:30 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Counter.h
SOURCES += Counter.cpp main.cpp
