######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 3 20:43:41 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TimerDialog.h
SOURCES += main.cpp TimerDialog.cpp
