######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 30 21:05:30 2010
######################################################################

TEMPLATE = app
TARGET = ../View
DEPENDPATH += .
INCLUDEPATH += .
QT           += network
QT           += xml
# Input
HEADERS += View.h Ball.h Racket.h BallWidget.h ViewHandler.h
SOURCES += main.cpp View.cpp Ball.cpp Racket.cpp BallWidget.cpp ViewHandler.cpp
