######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 21:16:09 2010
######################################################################
QT += network \
    xml \
    xmlpatterns

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BallDialog.h state.h
SOURCES += BallDialog.cpp main.cpp state.cpp

