# #####################################################################
# Automatically generated by qmake (2.01a) Tue Oct 12 12:45:01 2010
# #####################################################################
QT += network \
    xml \
    xmlpatterns
TARGET = BallDialog
TEMPLATE = app

# Input
HEADERS += BallDialog.h \
    state.h
SOURCES += BallDialog.cpp \
    main.cpp \
    state.cpp
OTHER_FILES += ipsettings.txt
