######################################################################
# Automatically generated by qmake (2.01a) ?? 14. ??? 23:46:53 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
