######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 10 22:37:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Ball.h
SOURCES += Ball.cpp main.cpp
