######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 30 16:59:38 2010
######################################################################

TEMPLATE = app
TARGET = ../Console
DEPENDPATH += .
INCLUDEPATH += .
QT           += network
QT           += xml

# Input
HEADERS += Console.h ConsoleHandler.h State.h
SOURCES += Console.cpp main.cpp ConsoleHandler.cpp State.cpp
