######################################################################
# Automatically generated by qmake (1.07a) Mon Nov 15 02:03:01 2010
######################################################################

TEMPLATE = app
TARGET = ../Control
QT += network xml
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Control.h
SOURCES += Control.cpp main.cpp
