######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 25 00:38:19 2010
######################################################################
QT += network
TEMPLATE = app
TARGET = Chat
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ChatDialog.h
SOURCES += ChatDialog.cpp main.cpp
