######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 5 11:23:46 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
