######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 30 21:09:06 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
