######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 13:49:36 2010
######################################################################

QT += testlib
TEMPLATE = app
TARGET = ../Test
DEPENDPATH += . ../src
INCLUDEPATH += . ../src

# Input
HEADERS += \ 
    test1.h \
    ../src/timers.h
SOURCES += \ 
    main.cpp \
    test1.cpp \
    ../src/timers.cpp
