######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 28 17:01:25 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Dialog.h MyThread.h
SOURCES += Dialog.cpp main.cpp MyThread.cpp
