######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 8 20:28:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CalcDialog.h MainWindow.h
SOURCES += CalcDialog.cpp main.cpp MainWindow.cpp
RESOURCES += images.qrc
