######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 30 00:05:52 2010
######################################################################

TEMPLATE = subdirs
TARGET = 
DEPENDPATH += . src test
INCLUDEPATH += . src test

# Input
HEADERS += src/Counter.h test/TestCounter.h
SOURCES += src/Counter.cpp src/main.cpp test/main.cpp test/TestCounter.cpp
SUBDIRS += src test
