######################################################################
# Automatically generated by qmake (2.01a) ?? 28. ??? 17:04:48 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
