######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 1 03:32:18 2010
######################################################################

QT += network xml

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyControl.h StateXmlHandler.h
SOURCES += MainControl.cpp MyControl.cpp StateXmlHandler.cpp
