######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 1 23:57:02 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += network xml

# Input
HEADERS += ControlDialog.h
SOURCES += ControlDialog.cpp main.cpp
