######################################################################
# Automatically generated by qmake (2.01a) ?? 3. ??? 20:29:58 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyDialog.h
SOURCES += main.cpp MyDialog.cpp
RESOURCES += 
