######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 01:59:29 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += TimerDialog.h
SOURCES += main.cpp TimerDialog.cpp
