######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 21:16:04 2010
######################################################################
QT += network \
    xml \
    xmlpatterns

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += reotecontrol.h
SOURCES += main.cpp reotecontrol.cpp
