######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 17 23:48:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
RESOURCES += task4.qrc
