######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 19 05:12:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calculator.h MainWindow.h
SOURCES += Calculator.cpp main.cpp MainWindow.cpp
