######################################################################
# Automatically generated by qmake (2.01a) ?? 27. ??? 23:51:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
