######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 28 12:04:46 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
