######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 30 08:31:07 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TimerDialog.h TimerThread.h
SOURCES += main.cpp TimerDialog.cpp TimerThread.cpp
