######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 24 04:01:51 2010
######################################################################

TEMPLATE = app
TARGET = task5
QT += network
HEADERS += NetDialog.h
SOURCES += main.cpp NetDialog.cpp
