######################################################################
# Automatically generated by qmake (2.01a) ?? 11. ??? 13:56:15 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ballwidget.h
SOURCES += ballwidget.cpp main.cpp
