######################################################################
# Automatically generated by qmake (2.01a) ?? 10. ??? 23:52:30 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Task3
INCLUDEPATH += .

# Input
HEADERS += ballwidget.h Task3/ballwidget.h
FORMS += Task3/ballwidget.ui
SOURCES += ballwidget.cpp main.cpp Task3/ballwidget.cpp Task3/main.cpp
RESOURCES += Task3/ballwidget.qrc
