######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 20:33:52 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyDialog.h
SOURCES += main.cpp MyDialog.cpp
