######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 21:04:41 2010
######################################################################

TEMPLATE = app
TARGET = ../task2
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TimerDialog.h
SOURCES += main.cpp TimerDialog.cpp
