######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 02:00:08 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += TestTimerDialog.h ../src/TimerDialog.h
SOURCES += main.cpp TestTimerDialog.cpp ../src/TimerDialog.cpp
