######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 18:28:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CalcDialog.h LoggerDialog.h
FORMS += LoggerDialog.ui
SOURCES += CalcDialog.cpp LoggerDialog.cpp main.cpp
