######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 19 01:23:09 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CalcDialog.h LoggerDialog.h
SOURCES += CalcDialog.cpp LoggerDialog.cpp main.cpp
