######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 1 05:16:26 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network xml

# Input
HEADERS += Arcanoid.h BouncedBall.h
SOURCES += Arcanoid.cpp BouncedBall.cpp main.cpp
