######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 26 20:59:11 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += a.cpp
