######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 23 00:07:04 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ChatDialog.h
SOURCES += ChatDialog.cpp main.cpp

QT += network
