######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 2 12:20:21 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += RemoteControlDialog.h
SOURCES += main.cpp RemoteControlDialog.cpp

QT += network xml
