######################################################################
# Automatically generated by qmake (1.07a) Mon Nov 28 14:16:44 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += dialog.h timer.h
SOURCES += dialog.cpp main.cpp timer.cpp
