######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 29 18:42:44 2010
######################################################################

TEMPLATE = app
TARGET = Timers
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += timers.h
SOURCES += main.cpp timers.cpp
