######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 20:38:50 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += test.h ../src/MyDialog.h
SOURCES += main.cpp test.cpp ../src/MyDialog.cpp
