######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 13:28:09 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TimerDialog.h
SOURCES += main.cpp TimerDialog.cpp
