######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 14 16:29:36 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+= network xml
# Input
HEADERS += controlattributs.h myParser.h pult.h
SOURCES += control.cpp myParser.cpp pult.cpp
