######################################################################
# Automatically generated by qmake (1.07a) Sat Oct 9 23:27:06 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += moveDialog.h
SOURCES += main.cpp moveDialog.cpp
