######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 27 12:21:39 2010
######################################################################

TEMPLATE = app
TARGET = ../table
DEPENDPATH += .
INCLUDEPATH += .
QT           += network xml

# Input
HEADERS += Table.h
SOURCES += main.cpp Table.cpp
