######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 9 23:59:33 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += balldialog.h
SOURCES += balldialog.cpp main.cpp
