######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 13:49:36 2010
######################################################################

TEMPLATE = app
TARGET = ../Timers
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += timers.h
SOURCES += main.cpp timers.cpp
