######################################################################
# Automatically generated by qmake (2.01a) ?? 14. ??? 23:47:35 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += dialogwrapper.h timertest.h ../src/dialog.h
SOURCES += dialogwrapper.cpp main.cpp timertest.cpp ../src/dialog.cpp
