######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 11 00:15:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BallWidget.h
SOURCES += BallWidget.cpp main.cpp
