######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 25 01:04:47 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += ChatDialog.h
SOURCES += ChatDialog.cpp main.cpp
