######################################################################
# Automatically generated by qmake (2.01a) ?? 27. ??? 23:24:21 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += task1.h
SOURCES += main.cpp task1.cpp
