######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 2 01:41:11 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyDialog.h
SOURCES += main.cpp MyDialog.cpp
