######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 17:09:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Table.h
SOURCES += main.cpp Table.cpp
