######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 24 21:20:59 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += ChatDialog.h
SOURCES += ChatDialog.cpp main.cpp
