######################################################################
# Automatically generated by qmake (2.01a) ?? 17. ??? 23:51:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculator.h main_window.h
SOURCES += calculator.cpp main.cpp main_window.cpp
