######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 27 12:21:28 2010
######################################################################

TEMPLATE = app
TARGET = ../pult
DEPENDPATH += .
INCLUDEPATH += .
QT           += network xml

# Input
HEADERS += Pult.h
SOURCES += main.cpp Pult.cpp
