######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 9 23:49:43 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calculator.h
SOURCES += Calculator.cpp main.cpp
