######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 17 20:49:57 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h LogWindow.h
SOURCES += CalculatorDialog.cpp LogWindow.cpp main.cpp
