######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 9 22:41:02 2010
######################################################################

TEMPLATE = app
TARGET = ../test_task2
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += TestTimer.h ../src/TimerDialog.h
SOURCES += main.cpp TestTimer.cpp ../src/TimerDialog.cpp
