######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 10 15:34:17 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Dialog.h
SOURCES += Dialog.cpp main.cpp
