######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 10 22:00:54 2010
######################################################################

TEMPLATE = app
TARGET = ../task7
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += Test.h ../src/Dialog.h
SOURCES += main.cpp Test.cpp ../src/Dialog.cpp
