######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 27 12:21:49 2010
######################################################################

TEMPLATE = subdirs
TARGET = 
DEPENDPATH += . tst src

# Input
SUBDIRS += tst src
