######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 7 15:48:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Ball.h MagicBall.h Racket.h SaxHandler.h State.h
SOURCES += Ball.cpp MagicBall.cpp main.cpp Racket.cpp SaxHandler.cpp State.cpp
QT += xml
QT += network
