######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 30 14:57:29 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Counter.h ThreadCounter.h
SOURCES += Counter.cpp main.cpp ThreadCounter.cpp
