######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 20 21:21:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT           += network

# Input
HEADERS += Chat.h
SOURCES += Chat.cpp Main.cpp
