# #####################################################################
# Automatically generated by qmake (2.01a) ?? ????. 29 00:01:33 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h \
            timer.h
SOURCES += dialog.cpp \
    main.cpp \
    timer.cpp
