######################################################################
# Automatically generated by qmake (2.01a) ?? 17. ??? 23:39:59 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calcdialog.h mainwindow.h
SOURCES += calcdialog.cpp main.cpp mainwindow.cpp
