######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 27 21:02:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TimeDialog.h TimeThread.h
SOURCES += main.cpp TimeDialog.cpp TimeThread.cpp
