######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 21:44:28 2010
######################################################################

TEMPLATE = subdirs
TARGET = 
DEPENDPATH += . src tst
INCLUDEPATH += . src tst

# Input
SUBDIRS += src tst
