######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 8 02:50:17 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += balldialog.h
SOURCES += balldialog.cpp main.cpp
