######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 7 01:27:43 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BallDialog.h
SOURCES += BallDialog.cpp main.cpp
