######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 9 22:43:25 2010
######################################################################

TEMPLATE = subdirs
TARGET = 
DEPENDPATH += . src test
INCLUDEPATH += . src test

# Input
HEADERS += src/MyDialog.h test/Test1.h
SOURCES += src/main.cpp src/MyDialog.cpp test/main.cpp test/Test1.cpp
SUBDIRS += src test
