######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 14 16:04:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Dialog.h
SOURCES += Dialog.cpp main.cpp
