######################################################################
# Automatically generated by qmake (2.01a) ?? 14. ??? 22:59:09 2010
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . 

# Input
HEADERS += timerdialogtest.h ../Task2/timerdialog.h
SOURCES += main.cpp timerdialogtest.cpp ../Task2/timerdialog.cpp
