######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 9 22:43:25 2010
######################################################################

TEMPLATE = subdirs
TARGET = 
DEPENDPATH += . src test

# Input
SUBDIRS += src test
