# #####################################################################
# Automatically generated by qmake (2.01a) Tue Sep 28 23:21:24 2010
# #####################################################################
TEMPLATE = app
TARGET = ../tests
DEPENDPATH += .
INCLUDEPATH += .
QT += testlib
HEADERS += timerstest.h \
    ../src/timersdialog.h
SOURCES += timerstest.cpp \
    ../src/timersdialog.cpp \
    main.cpp
