######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 24 16:31:20 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ChatDialog.h
SOURCES += ChatDialog.cpp main.cpp
QT += network
