######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 1 15:32:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network xml
# Input
HEADERS += attributs.h Ball.h Game.h myHandler.h Racket.h
SOURCES += Ball.cpp Game.cpp main.cpp myHandler.cpp
